### ISSUE TITLE
SAML 1.1 - the moment variable "now" is mutated for AuthenticationInstant

### ISSUE THREAD

**Issue by georgibakken** [auth0/node-saml#32]
In [line 69](https://github.com/auth0/node-saml/blob/master/lib/saml11.js#L69) the timestamp variable `now` has time added to it, which mutates the original time.

`now` is then re-used later when setting the `AuthenticationInstant`, however it is not the current time being set, but the mutated one. This leads to the `AuthenticationInstant` having the same time as the `NotOnOrAfter` attribute. 

A possible fix is to re-initialise the `now` variable, after it's mutated.

**Comment by hauntingEcho** [comment]
another possible fix would be to use `now.clone().add` instead of `now.add`, [like 2.0 does](https://github.com/auth0/node-saml/blob/master/lib/saml20.js#L111)

**Comment by georgibakken** [comment]
Nice - thats a good fix. Thank you
