### ISSUE TITLE
NSP Issue regarding ReDOS

### ISSUE THREAD

**Issue by alexlapinski** [auth0/node-saml#38]
Hi, we currently make use of samlp, which in turn makes use of this package "saml" on npm.

It looks like the open NSP issue for ReDOS via momentjs requires a package update in your dependencies. (https://nodesecurity.io/advisories/532)

I was wondering if you had any plans in the near future to update your momentjs dependency to 2.19.3 (patched version of moment).

**Comment by spalger** [comment]
Bump :)

**Comment by nlfiedler** [comment]
Any hope of Auth0 noticing this and fixing it? It would seem to be a simple matter of updating to the latest release of moment.

**Comment by luuuis** [comment]
Fixed in https://github.com/auth0/node-saml/pull/60 and released as https://www.npmjs.com/package/saml/v/0.14.0
