### ISSUE TITLE
Dependency Moment:2.15.2 is vulnerable according to nodesecurity.io

### ISSUE THREAD

**Issue by Dobbychen** [auth0/node-saml#41]
This module is depending on "moment": ["2.15.2"](https://github.com/auth0/node-saml/blob/master/package.json#L18), which is reported as vulnerable to a low severity regular expression denial of service vulnerability.

Suggest to update to latest moment.js package
>>>
Vulnerable: <2.19.3
Patched: >=2.19.3
Regular Expression Denial of Service
Module: moment
Published: November 27th, 2017
Reported by: Cristian-Alexandru Staicu
CVE-NONE

https://nodesecurity.io/advisories/532

**Comment by danielwpz** [comment]
please patch it asap guys!

**Comment by luuuis** [comment]
Fixed in https://github.com/auth0/node-saml/pull/60
