### ISSUE TITLE
Vulnerability issue in moment in versions < 2.19.3

### ISSUE THREAD

**Issue by pavankumartp** [auth0/node-saml#59]
Can you update the "moment" dependency in the "saml"  module to 2.19.3 or later so that the vulnerability is covered?
See https://github.com/moment/moment/issues/4163 for more details.
Our company's security scan identified this and asking us to change. I did not think there is any other way than asking you to change the version of moment.

Thanks so much.

best regards,
Pavan.

**Comment by TimFerrell** [comment]
Thanks for raising this, I've opened https://github.com/auth0/node-saml/pull/60 to resolve.

**Comment by TimFerrell** [comment]
Thanks for reporting. The fix is merged.

**Comment by pavankumartp** [comment]
In the npm registry, the version is still 0.13.0. I guess this would still not consider the latest moment version? Would you plan to then push the latest to npm?

**Comment by TimFerrell** [comment]
Latest tag has been pushed: https://www.npmjs.com/package/saml/v/0.14.0
