### ISSUE TITLE
Update xml-encryption version to resolve node-forge vulnerability

### ISSUE THREAD

**Issue by v2balasu** [auth0/node-saml#67]
### Description

Outdated xml-encryption dependency contains a version of node-forge with 'High' severity vulnerability.  The 'xml-encryption' dependency should be updated to v1.2.1.

### Reproduction

Running an npm audit produces the following output:

~~~

Run  npm install xml-encryption@1.2.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Prototype Pollution in node-forge

  Package         node-forge

  Dependency of   xml-encryption

  Path            xml-encryption > node-forge

  More info       https://npmjs.com/advisories/1561
~~~

### Environment

- **Version of this library used:** 0.15.0

**Comment by forrest-ua** [comment]
`xml-encryption` dependency has been updated in https://github.com/auth0/node-saml/pull/72.
