### ISSUE TITLE
Update xml-crypto from ~1.0.1 to 2.0.0 to resolve vulnerability GHSA-c27r-x354-4m68

### ISSUE THREAD

**Issue by matsbauer711** [auth0/node-saml#70]
### Description

node-saml is dependent on "xml-crypto": "~1.0.1"

according to https://github.com/yaronn/xml-crypto/security/advisories/GHSA-c27r-x354-4m68

Affected versions <= 1.5.3
Patched versions 2.0.0

Impact
An attacker can inject an HMAC-SHA1 signature that is valid using only knowledge of the RSA public key. This allows bypassing signature validation.

Patches
Version 2.0.0 has the fix.

Workarounds
The recommendation is to upgrade. In case that is not possible remove the 'http://www.w3.org/2000/09/xmldsig#hmac-sha1' entry from SignedXml.SignatureAlgorithms.

### Reproduction

no reproduction

### Environment

node-saml 0.15.0 depending on "xml-crypto": "~1.0.1"

(please note: this is my first ever issue I open on github)

**Comment by luuuis** [comment]
Thank you. This was released in https://github.com/auth0/node-saml/releases/tag/v1.0.1.
