### ISSUE TITLE
[Question] Is the SAML2 assertion creation implementation production ready?

### ISSUE THREAD

**Issue by petermikitsh** [auth0/node-saml#9]
The documentation outlines support for SAML 1.1 assertion creation, but I see a SAML 2.0 implementation included. I'm thinking either the documentation out-of-date, or it's not production ready (hoping it's the former). Please clarify at your earliest convenience. Thanks!

**Comment by siacomuzzi** [comment]
Both versions are supported (we need to update the doc accordingly).
